dist: trusty
sudo: false
language: node_js
node_js: node
deploy:
  provider: npm
  email: koczkatamas@gmail.com
  api_key:
    secure: "BKmllFXVBgP+TS9/aKS7tWr2H5nGDe6/2DRrUhjXcYgnoQ8yurQb9IhHZAVIPVG9oBwlHt3O3RzVBsOnKGuwf0H3fnOyEPPGI6hynh0oVQhlCjEnkatWhiuUtq0aAn0vOJoW2y5/oR+TCCVKDumYYjoEbIYoqvXLm78TqZ8g9aTdukVs54aCwgY7Lul+w/qvAmw5ZxgotSoWaN0Ezf9preY6ySQL+AY+/SaJ/sB4GTJG0pmiKNaWQqE0xqbdO1CD0fcRfbn683oji2NpIcPs0t7z1pPZNyxmQ9fLXPHMEb1ydzMdt94dGF/MSQ/Z2m5Jf74+29u08V8zQzP0I2Ta9xyAkU0tQs0JK0R/i4WUx2oqeBZ7mDZR2FS9H5g+P8R/iGrCIgUj5n0W7JrcuJgXoQBURFRIamt+Cc7cTfZ2cAvtBEjo71MfKemNW90z4bE3CBa3RJrVibh0+pcgSHRxT8wT6KCNZPEQzOassRdDnlecL2yB+cH/3K4s4Mvp9Fu7DfTJlG2BCJRHIVwrtIdzgp4KNj//cjViWgKr3NYFLfhuMFMaqIDaVlWzOqzwiwzk19AZ2GfWW99SpVMpyCxhQd4H3ATrrGqpAo7c8T6gjaf0Dzy1BPAODF7Cc0MN8OU/HEzDbJtDQ1NOiLvOZN57q9HLsqp/OK1SvFXUDu2Q6QA="
  on:
    tags: true
